# Site settings
title: Juliana Desenvovledora
description: Portfólio da Juliana Portilho 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Juliana Portilho
user_description: Desenvolvedora motivada, com 2 anos de experiência progressiva no setor de manutenção e inovação. Possuo conhecimentos em , C#, Java, SharePoint,  angular,  Ionic, Oracle, MySQL, chatbot, gestão de projetos, CAPPM, Project,  Fluxo de projetos e cronogramas. Proativa, autodidata, sempre buscando novos desafios e novidades em TI.
user_title: Desenvolvedora FrontEnd
email: julianaport.rogerio@gmail.com
github_username:  julianaPort


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

theme: jekyll-theme-cayman